function main_glove_selection_gui
% MAIN_GLOVE_SELECTION_GUI - Main menu for glove defect detection system
%
% Allows user to select glove type and launch appropriate detection system

    clc;
    close all;
    
    % ===== CREATE MAIN WINDOW =====
    fig = figure('Name', 'Glove Defect Detection - Main Menu', ...
                 'NumberTitle', 'off', ...
                 'Position', [300 200 800 600], ...
                 'Resize', 'on', ...
                 'MenuBar', 'none', ...
                 'Color', [0.1 0.1 0.1], ...
                 'CloseRequestFcn', @closeGUI);
    
    % ===== TITLE PANEL =====
    titlePanel = uipanel('Parent', fig, ...
                         'Units', 'pixels', ...
                         'Position', [50 450 700 120], ...
                         'BackgroundColor', [0.15 0.15 0.15], ...
                         'BorderType', 'none');
    
    % Main title
    uicontrol('Parent', titlePanel, ...
              'Style', 'text', ...
              'String', 'GLOVE DEFECT DETECTION SYSTEM', ...
              'Position', [50 60 600 40], ...
              'FontSize', 20, ...
              'FontWeight', 'bold', ...
              'ForegroundColor', 'white', ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % Subtitle
    uicontrol('Parent', titlePanel, ...
              'Style', 'text', ...
              'String', 'Select Glove Type to Begin Inspection', ...
              'Position', [50 20 600 30], ...
              'FontSize', 12, ...
              'ForegroundColor', [0.7 0.7 0.7], ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % ===== GLOVE TYPE SELECTION PANEL =====
    selectionPanel = uipanel('Parent', fig, ...
                             'Units', 'pixels', ...
                             'Position', [50 100 700 320], ...
                             'Title', 'Choose Glove Type', ...
                             'FontSize', 14, ...
                             'FontWeight', 'bold', ...
                             'BackgroundColor', [0.15 0.15 0.15], ...
                             'ForegroundColor', 'white');
    
    % Button dimensions
    btnWidth = 300;
    btnHeight = 60;
    xLeft = 40;
    xRight = 360;
    
    % ===== LATEX GLOVE BUTTON (TOP LEFT) =====
    uicontrol('Parent', selectionPanel, ...
              'Style', 'pushbutton', ...
              'String', 'LATEX GLOVE', ...
              'Position', [xLeft 220 btnWidth btnHeight], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.3 0.6 0.9], ...
              'ForegroundColor', 'white', ...
              'Callback', @launchLatexGlove);
    
    % Latex description
    uicontrol('Parent', selectionPanel, ...
              'Style', 'text', ...
              'Position', [xLeft 195 btnWidth 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0.6 0.6 0.6], ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % ===== NITRILE GLOVE BUTTON (TOP RIGHT) =====
    uicontrol('Parent', selectionPanel, ...
              'Style', 'pushbutton', ...
              'String', 'NITRILE GLOVE', ...
              'Position', [xRight 220 btnWidth btnHeight], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.5 0.3 0.8], ...
              'ForegroundColor', 'white', ...
              'Callback', @launchNitrileGlove);
    
    % Nitrile description
    uicontrol('Parent', selectionPanel, ...
              'Style', 'text', ...
              'Position', [xRight 195 btnWidth 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0.6 0.6 0.6], ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % ===== COTTON GLOVE BUTTON (BOTTOM LEFT) =====
    uicontrol('Parent', selectionPanel, ...
              'Style', 'pushbutton', ...
              'String', 'COTTON GLOVE', ...
              'Position', [xLeft 110 btnWidth btnHeight], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.2 0.7 0.3], ...
              'ForegroundColor', 'black', ...
              'Callback', @launchCottonGlove);
    
    % Cotton description
    uicontrol('Parent', selectionPanel, ...
              'Style', 'text', ...
              'Position', [xLeft 85 btnWidth 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0.6 0.6 0.6], ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % ===== RUBBER GLOVE BUTTON (BOTTOM RIGHT) =====
    uicontrol('Parent', selectionPanel, ...
              'Style', 'pushbutton', ...
              'String', 'RUBBER GLOVE', ...
              'Position', [xRight 110 btnWidth btnHeight], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.9 0.7 0.2], ...
              'ForegroundColor', 'black', ...
              'Callback', @launchRubberGlove);
    
    % Rubber description
    uicontrol('Parent', selectionPanel, ...
              'Style', 'text', ...
              'Position', [xRight 85 btnWidth 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0.6 0.6 0.6], ...
              'BackgroundColor', [0.15 0.15 0.15]);
    
    % ===== INFO TEXT =====
    uicontrol('Parent', selectionPanel, ...
              'Style', 'text', ...
              'String', {'Each glove type uses specialized detection algorithms', ...
                         'optimized for material properties and common defects'}, ...
              'Position', [50 20 600 50], ...
              'FontSize', 10, ...
              'ForegroundColor', [0.5 0.8 1.0], ...
              'BackgroundColor', [0.15 0.15 0.15], ...
              'HorizontalAlignment', 'center');
    
    % ===== EXIT BUTTON =====
    uicontrol('Parent', fig, ...
              'Style', 'pushbutton', ...
              'String', 'EXIT', ...
              'Position', [300 30 200 50], ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.8 0.2 0.2], ...
              'ForegroundColor', 'white', ...
              'Callback', @closeGUI);
    
    % ===== CALLBACK FUNCTIONS =====
    
    function launchLatexGlove(~, ~)
        try
            fprintf('Launching Latex Glove Detection System...\n');
            
            % Add Latex Glove folder to path if needed
            latexFolder = fullfile(pwd, 'Latex Glove');
            if exist(latexFolder, 'dir')
                addpath(latexFolder);
            end
            
            latex_glove_gui;  % Your existing GUI
        catch ME
            errordlg(['Failed to launch Latex Glove system: ' ME.message], ...
                     'Launch Error');
        end
    end
    
    function launchNitrileGlove(~, ~)
        try
            fprintf('Launching Nitrile Glove Detection System...\n');
            
            % Add Nitrile Glove folder to path if needed
            nitrileFolder = fullfile(pwd, 'Nitrile Glove');
            if exist(nitrileFolder, 'dir')
                addpath(nitrileFolder);
            end
            
            % Check if file exists
            if exist('nitrile_glove_gui.m', 'file')
                nitrile_glove_gui;
            else
                msgbox({'Nitrile Glove detection system not yet implemented.', ...
                        '', ...
                        'This feature will use the same detection algorithms', ...
                        'as Latex gloves (both are blue synthetic materials).'}, ...
                       'Coming Soon', 'warn');
            end
        catch ME
            errordlg(['Failed to launch Nitrile Glove system: ' ME.message], ...
                     'Launch Error');
        end
    end
    
    function launchCottonGlove(~, ~)
        try
            fprintf('Launching Cotton Glove Detection System...\n');
            
            % Add Cotton Glove folder to path if needed
            cottonFolder = fullfile(pwd, 'Cotton Glove');
            if exist(cottonFolder, 'dir')
                addpath(cottonFolder);
            end
            
            cotton_glove_gui;  %  cotton GUI
        catch ME
            errordlg(['Failed to launch Cotton Glove system: ' ME.message], ...
                     'Launch Error');
        end
    end
    
    function launchRubberGlove(~, ~)
        try
            fprintf('Launching Rubber Glove Detection System...\n');
            
            % Add Rubber Glove folder to path if needed
            rubberFolder = fullfile(pwd, 'Rubber Glove');
            if exist(rubberFolder, 'dir')
                addpath(rubberFolder);
            end
            
            % Check if file exists
            if exist('rubber_glove_gui.m', 'file')
                rubber_glove_gui;
            else
                msgbox({'Rubber Glove detection system not yet implemented.', ...
                        '', ...
                        'This feature will require yellow/green color', ...
                        'detection algorithms (currently optimized for blue).'}, ...
                       'Coming Soon', 'warn');
            end
        catch ME
            errordlg(['Failed to launch Rubber Glove system: ' ME.message], ...
                     'Launch Error');
        end
    end
    
    function closeGUI(~, ~)
        fprintf('Closing Glove Defect Detection System...\n');
        delete(fig);
    end
    
end