function MainMenu()
    % Industrial-Style Main Menu for Glove Inspection System
    % Matches the aesthetic of RubberGloveDDSystem
    
    % Color scheme (matching RubberGloveDDSystem)
    BGColor = [0.15, 0.15, 0.15];      % Dark background
    SCColor = [0.95, 0.85, 0.10];      % Yellow accent
    PanelColor = [0.20, 0.20, 0.20];   % Slightly lighter panels
    
    % Get screen resolution and calculate scaling
    screenSize = get(0, 'ScreenSize'); % [left, bottom, width, height]
    screenHeight = screenSize(4);
    
    % Base design is for 1080p (1920x1080)
    % Scale factor based on screen height
    if screenHeight <= 768  % 720p or lower
        scaleFactor = 0.7;
    elseif screenHeight <= 1080  % 1080p
        scaleFactor = 0.85;
    else  % 1440p, 4K, etc.
        scaleFactor = 1.0;
    end
    
    % Scaled dimensions
    baseWidth = 800;
    baseHeight = 600;
    figWidth = round(baseWidth * scaleFactor);
    figHeight = round(baseHeight * scaleFactor);
    
    % Center the window on screen
    figX = round((screenSize(3) - figWidth) / 2);
    figY = round((screenSize(4) - figHeight) / 2);
    
    % Create main menu figure
    menuFig = uifigure('Name', 'Glove Inspection System', ...
                       'Position', [figX figY figWidth figHeight], ...
                       'Color', BGColor, ...
                       'Resize', 'off');
    
    % Title Panel (matching RubberGloveDDSystem style)
    titlePanel = uipanel(menuFig, ...
                        'Position', [20*scaleFactor 520*scaleFactor 760*scaleFactor 60*scaleFactor], ...
                        'BackgroundColor', SCColor, ...
                        'BorderType', 'line');
    
    uilabel(titlePanel, ...
            'Text', 'GLOVE DEFECT DETECTION SYSTEM', ...
            'Position', [0 0 760*scaleFactor 60*scaleFactor], ...
            'FontSize', round(28*scaleFactor), 'FontWeight', 'bold', ...
            'HorizontalAlignment', 'center', ...
            'FontColor', [0 0 0]);
    
    % Subtitle
    uilabel(menuFig, ...
            'Text', 'SELECT GLOVE TYPE TO BEGIN INSPECTION', ...
            'Position', [20*scaleFactor 470*scaleFactor 760*scaleFactor 30*scaleFactor], ...
            'FontSize', round(14*scaleFactor), 'FontWeight', 'bold', ...
            'HorizontalAlignment', 'center', ...
            'FontColor', SCColor);
    
    % Main content panel
    contentPanel = uipanel(menuFig, ...
                          'Position', [20*scaleFactor 20*scaleFactor 760*scaleFactor 440*scaleFactor], ...
                          'BackgroundColor', PanelColor, ...
                          'BorderType', 'line', ...
                          'HighlightColor', SCColor);
    
    % Button dimensions and spacing (scaled)
    btnWidth = round(680 * scaleFactor);
    btnHeight = round(80 * scaleFactor);
    btnSpacing = round(30 * scaleFactor);
    startY = round(310 * scaleFactor);
    btnX = round(40 * scaleFactor);
    
    % RUBBER GLOVE BUTTON
    rubberBtn = uibutton(contentPanel, 'push', ...
                        'Text', '◄ RUBBER GLOVE DEFECT DETECTION', ...
                        'Position', [btnX startY btnWidth btnHeight], ...
                        'FontSize', round(18*scaleFactor), 'FontWeight', 'bold', ...
                        'BackgroundColor', [0.00, 0.75, 0.90], ...
                        'FontColor', [0 0 0], ...
                        'ButtonPushedFcn', @(~,~) launchRubberGlove(menuFig));
    
    % Add description label
    uilabel(contentPanel, ...
            'Text', 'Detects: Sticky Fingers, Burn Marks, Holes', ...
            'Position', [round(50*scaleFactor) startY-round(5*scaleFactor) round(660*scaleFactor) round(20*scaleFactor)], ...
            'FontSize', round(11*scaleFactor), 'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'left');
    
    % NITRILE GLOVE BUTTON
    nitrileBtn = uibutton(contentPanel, 'push', ...
                         'Text', '◄ NITRILE GLOVE DEFECT DETECTION', ...
                         'Position', [btnX startY-btnHeight-btnSpacing btnWidth btnHeight], ...
                         'FontSize', round(18*scaleFactor), 'FontWeight', 'bold', ...
                         'BackgroundColor', [0.70, 0.95, 0.00], ...
                         'FontColor', [0 0 0], ...
                         'Enable', 'off');
    
    uilabel(contentPanel, ...
            'Text', 'Coming Soon - System Under Development', ...
            'Position', [round(50*scaleFactor) startY-btnHeight-btnSpacing-round(5*scaleFactor) round(660*scaleFactor) round(20*scaleFactor)], ...
            'FontSize', round(11*scaleFactor), 'FontColor', [0.5 0.5 0.5], ...
            'HorizontalAlignment', 'left');
    
    % COTTON GLOVE BUTTON
    cottonBtn = uibutton(contentPanel, 'push', ...
                        'Text', '◄ COTTON GLOVE DEFECT DETECTION', ...
                        'Position', [btnX startY-2*(btnHeight+btnSpacing) btnWidth btnHeight], ...
                        'FontSize', round(18*scaleFactor), 'FontWeight', 'bold', ...
                        'BackgroundColor', [0.95, 0.20, 0.30], ...
                        'FontColor', [1 1 1], ...
                        'Enable', 'off');
    
    uilabel(contentPanel, ...
            'Text', 'Coming Soon - System Under Development', ...
            'Position', [round(50*scaleFactor) startY-2*(btnHeight+btnSpacing)-round(5*scaleFactor) round(660*scaleFactor) round(20*scaleFactor)], ...
            'FontSize', round(11*scaleFactor), 'FontColor', [0.5 0.5 0.5], ...
            'HorizontalAlignment', 'left');
    
    % Footer info
    uilabel(contentPanel, ...
            'Text', '© 2026 IPPR Assignment | Industrial Glove Quality Control', ...
            'Position', [btnX round(10*scaleFactor) btnWidth round(20*scaleFactor)], ...
            'FontSize', round(10*scaleFactor), ...
            'HorizontalAlignment', 'center', ...
            'FontColor', [0.5 0.5 0.5]);
end

function launchRubberGlove(menuFig)
    % STEP 1: Hide the main menu
    menuFig.Visible = 'off';
    
    % STEP 2: Launch your RubberGloveDDSystem app
    app = RubberGloveDDSystem();
    
    % STEP 3: Set the callback - when back button is clicked
    app.ReturnToMenuCallback = @() returnToMenu(menuFig);
end

function returnToMenu(menuFig)
    % STEP 4: Show the main menu again when returning
    if isvalid(menuFig)
        menuFig.Visible = 'on';
    end
end
